name: Upload Python Package

on:
  workflow_dispatch:

jobs:
  python-build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@main

      - name: Initialize Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9  

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}  
          repository_url: https://upload.pypi.org/legacy/