name: Upload Python Package

on:
  workflow-dispatch:  # Permette di eseguire manualmente il workflow 

jobs:
  python-build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@main

      - name: Initialize Python 
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'  

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade pip

      - name: Build package
          python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          username: __token__
          password: ${{ secrets.PYPI_PASSWORD }} 
          repository_url: https://upload.pypi.org/legacy/